# Generated by Django 4.0.3 on 2022-03-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_date', models.DateField()),
                ('debit_status', models.IntegerField(choices=[(0, 'not paid'), (1, 'paid')], default=0, verbose_name='order status')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debit', to='customers.customer')),
            ],
        ),
    ]
