# Generated by Django 4.0.3 on 2022-03-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_made_by_alter_order_made_for'),
        ('customers', '0002_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_debit', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debit',
            name='debit_date',
            field=models.DateField(verbose_name='debit date'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='debit_status',
            field=models.IntegerField(choices=[(0, 'not paid'), (1, 'paid')], default=0, verbose_name='debit status'),
        ),
    ]
