# Generated by Django 4.0.3 on 2022-04-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_debit_order_alter_debit_debit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debit', to='customers.customer'),
        ),
    ]
