# Generated by Django 4.0.3 on 2022-04-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_debit_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
