# Generated by Django 4.0.3 on 2022-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_1',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_2',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address 2'),
        ),
    ]
