# Generated by Django 4.0.3 on 2022-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_1',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_2',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
