# Generated by Django 4.0.3 on 2022-03-15 12:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address_1_alter_user_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'theres already a user that have this phone number!'}, max_length=128, region='PS', unique=True, verbose_name='Phone Number'),
        ),
    ]
