# Generated by Django 4.0.3 on 2022-03-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'theres already a user that have this phone number!'}, max_length=128, region='PS', unique=True, verbose_name='Phone Number')),
                ('address_1', models.CharField(blank=True, max_length=400, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=400, verbose_name='Address 2')),
                ('salary_per_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salary per day')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_date', models.DateField(auto_now_add=True, verbose_name='absence date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid ?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_absence', to='employees.employee')),
            ],
        ),
    ]
